#!/usr/bin/env bash

OTP=123456
TAG=latest

npm publish dist/packages/core --access public --tag "${TAG}"
npm publish dist/packages/modal-ui --access public --tag "${TAG}"
npm publish dist/packages/modal-ui-js --access public --tag "${TAG}"
npm publish dist/packages/default-wallets --access public --tag "${TAG}"
npm publish dist/packages/wallet-utils --access public --tag "${TAG}"
npm publish dist/packages/near-wallet --access public --tag "${TAG}"
npm publish dist/packages/my-near-wallet --access public --tag "${TAG}"
npm publish dist/packages/sender --access public --tag "${TAG}"
npm publish dist/packages/math-wallet --access public --tag "${TAG}"
npm publish dist/packages/nightly --access public --tag "${TAG}"
npm publish dist/packages/ledger --access public --tag "${TAG}"
npm publish dist/packages/wallet-connect --access public --tag "${TAG}"
npm publish dist/packages/nightly-connect --access public --tag "${TAG}"
npm publish dist/packages/meteor-wallet --access public --tag "${TAG}"
npm publish dist/packages/here-wallet --access public --tag "${TAG}"
npm publish dist/packages/coin98-wallet --access public --tag "${TAG}"
npm publish dist/packages/nearfi --access public --tag "${TAG}"
npm publish dist/packages/opto-wallet --access public --tag "${TAG}"
npm publish dist/packages/finer-wallet --access public --tag "${TAG}"
npm publish dist/packages/welldone-wallet --access public --tag "${TAG}"
npm publish dist/packages/neth --access public --tag "${TAG}"
npm publish dist/packages/account-export --access public --tag "${TAG}"
npm publish dist/packages/narwallets --access public --tag "${TAG}"
npm publish dist/packages/xdefi --access public --tag "${TAG}"
npm publish dist/packages/near-snap --access public --tag "${TAG}"
